apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/homepage
patches:
  - target:
      kind: Ingress
      name: homepage
    patch: |
      - op: replace
        path: "/spec/rules/0/host"
        value: "homelab"
      - op: replace
        path: "/spec/rules/0/http/paths/0/path"
        value: "/homepage"

  - target:
      kind: Deployment
      name: homepage
    patch: |
      - op: replace
        path: "/spec/template/spec/containers/0/env/0/value"
        value: "homelab"

  - target:
      kind: ConfigMap
      name: homepage
    patch: |
      - op: replace
        path: "/data/settings.yaml"
        value: |
          base: /homepage
          title: My custom homelab Homepage
          theme: dark
          headerStyle: clean
