apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/homepage
patches:
  - target:
      kind: Ingress
      name: homepage
    patch: |
      - op: replace
        path: "/spec/rules/0/host"
        value: "homelab"
      - op: replace
        path: "/spec/rules/0/http/paths/0/path"
        value: "/"

  - target:
      kind: Deployment
      name: homepage
    patch: |
      - op: replace
        path: "/spec/template/spec/containers/0/env/0/value"
        value: "homelab"

  - patch: |
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: homepage
        namespace: homepage
      data:
        settings.yaml: |
          title: My custom homelab Homepage
          theme: dark
          headerStyle: clean
